// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { AppDatabase } from './types';

const SUPABASE_URL = "https://zjaqjxqtbwrkhijdlvyo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpqYXFqeHF0Yndya2hpamRsdnlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MzE4MTAsImV4cCI6MjA3MDUwNzgxMH0.3ShbEcaaAYMt9JTxwKCzw3c6pCCt4Oatdo2FaeYTOkk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<AppDatabase>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});